### ISSUE TITLE
When will the code be updated?

### ISSUE THREAD

**Issue by yonghoonjeon** [microsoft/PersonalizedFL#10]
Hello, thank you for sharing excellent repository.
I'm wondering when the source code for the CLIP-based model based on the paper will be uploaded. (https://arxiv.org/abs/2302.13485)

**Comment by jindongwang** [comment]
Thanks for asking! The code will be updated in a month, once it got accepted by the journal.

**Comment by yonghoonjeon** [comment]
Thank you for your prompt reply! 
I will close this issue, and then keep an eye on it.
