### ISSUE TITLE
Where is code about "FedCLIP: Fast Generalization and Personalization for CLIP in Federated Learning"

### ISSUE THREAD

**Issue by White1973** [microsoft/PersonalizedFL#12]
Hello, sorry to bother you.
FedCLIP is really good work in prompt learning and federated learning. I find the relevant code link of FedCLIP is this repo in the website "paper with code". But I cannot find any information about FedCLIP in this repo.

Could you tell me where is the code for FedCLIP?

**Comment by jindongwang** [comment]
Thanks for asking. The code of FedCLIP will be released after NeurIPS deadline. Please give the student some time to submit his NeurIPS paper:)

**Comment by jindongwang** [comment]
Please give us more time to prepare the code since the student was busy with his graduation recently.

**Comment by jindongwang** [comment]
@White1973 The code for FedCLIP is released now. You can find it here: https://github.com/microsoft/PersonalizedFL/tree/main/fedclip
