### ISSUE TITLE
关于metaFed的一点问题

### ISSUE THREAD

**Issue by gitCoder1024** [microsoft/PersonalizedFL#13]
在init_model_flag中所有client已经完成了一个联邦round，然后mian.py中iters-1
`algclass.init_model_flag(train_loaders, val_loaders)
args.iters = args.iters-1 # 在init时，已经训练了一轮`
紧接着在接下来再进行client训练时，已经可以开始知识蒸馏了，为什么还要在metafed.py的client_train方法中加round==0（第0轮不是已经在init_model_flag时就进行了吗）的限制，期待您的回复

**Comment by jindongwang** [comment]
@lw0517

**Comment by lw0517** [comment]
> 在init_model_flag中所有client已经完成了一个联邦round，然后mian.py中iters-1 `algclass.init_model_flag(train_loaders, val_loaders) args.iters = args.iters-1 # 在init时，已经训练了一轮` 紧接着在接下来再进行client训练时，已经可以开始知识蒸馏了，为什么还要在metafed.py的client_train方法中加round==0（第0轮不是已经在init_model_flag时就进行了吗）的限制，期待您的回复

这里影响并不大，我们之所以加round=0，是为了说明联邦训练从这里开始，刚开始的时候第一个联邦端直观上来讲不存在老师模型，当然也可以把这个限制去掉，这个限制不是特别关键。
