### ISSUE TITLE
关于Train val splits and h5py files pre-read文件夹的使用

### ISSUE THREAD

**Issue by tianguang2525** [microsoft/PersonalizedFL#31]
您好！请问数据集文件中，train val splits and h5py files pre-read文件夹下的.kfold.txt,hdf5,.txt文件应当如何使用，非常感谢！

**Comment by jindongwang** [comment]
@lw0517 有时间可以回答一下

**Comment by lw0517** [comment]
> 您好！请问数据集文件中，train val splits and h5py files pre-read文件夹下的.kfold.txt,hdf5,.txt文件应当如何使用，非常感谢！

本项目没有用到这个文件夹train val splits and h5py files pre-read，直接用kfold即可

**Comment by tianguang2525** [comment]
> > 您好！请问数据集文件中，train val splits and h5py files pre-read文件夹下的.kfold.txt,hdf5,.txt文件应当如何使用，非常感谢！
> 
> 本项目没有用到这个文件夹train val splits and h5py files pre-read，直接用kfold即可

好的，谢谢！
