### ISSUE TITLE
在FedAP中，获得预训练模型的过程中是否存在数据隐私问题？

### ISSUE THREAD

**Issue by aosodofogo** [microsoft/PersonalizedFL#33]
您好！我是否需要使用另一组数据用于获得预训练模型
![image](https://github.com/microsoft/PersonalizedFL/assets/103180227/ed3dbbcb-98a5-4282-b6c5-82c1005d13d0)

**Comment by jindongwang** [comment]
这个不存在的，没有用隐私数据。你没理解FedAP。建议重新读一下paper。

**Comment by aosodofogo** [comment]
好的，感谢您的回复
