### ISSUE TITLE
关于non_iid_alpha这个参数的意义

### ISSUE THREAD

**Issue by heqinze** [microsoft/PersonalizedFL#37]
做实验时想设置一种满足客户端之间数据“非独立同分布”的情况，所以想请问non_iid_alpha以及non_iid_dirichlet这两个参数的意义，以及它们是否能帮助我划分满足“非独立同分布“这种情况的数据？非常感谢

**Comment by lw0517** [comment]
我们设置了不同的数据划分形式，默认是non_iid_dirichlet，这个时候可以通过对应的non_iid_alpha设置划分的分布差异程度，值越小，分布差异越大

**Comment by heqinze** [comment]
这样的话，我可以得到各个客户端之间数据分布的具体信息吗？比如像下图的一个covid数据分布情况
![ef468d90490c7225a8868ec5652aae6](https://github.com/microsoft/PersonalizedFL/assets/47132334/d3366bab-789d-4a92-80ec-63c67dd37608)
