### ISSUE TITLE
Bug in FedClip 

### ISSUE THREAD

**Issue by GongShuai8210** [microsoft/PersonalizedFL#38]
Thanks for your work! In the process of reproducing the FedClip, I found that the training accuracy of each epoch does not change when test_envs is 3. Strangely, when I change the position of the domain in the dataset, [‘art_painting’, ‘cartoon’, ‘photo’, ‘sketch’] ——>['sketch, ‘art_painting’, ‘cartoon’, ‘photo’], and let test_envs still set to 3, this problem still occurs. This phenomenon also exists in other datasets. I tried to locate the bug, but I still didn’t find it.

============ Train epoch 0 ============
100%|██████████| 39/39 [00:03<00:00, 12.25it/s]
100%|██████████| 44/44 [00:03<00:00, 12.64it/s]
100%|██████████| 32/32 [00:02<00:00, 12.25it/s]
 Site-0| Train Acc: 97.3127
 Site-0| Val  Acc: 97.5550
 Site-1| Train Acc: 99.2176
 Site-1| Val  Acc: 99.3590
 Site-2| Train Acc: 100.0000
 Site-2| Val  Acc: 100.0000
 Test site-0| Test Acc: 97.5550
 Test site-1| Test Acc: 98.7179
 Test site-2| Test Acc: 99.7006
 Test site-3| Test Acc: 89.3612
One epoc takes time: 32.73s
============ Train epoch 1 ============
100%|██████████| 39/39 [00:02<00:00, 13.66it/s]
100%|██████████| 44/44 [00:03<00:00, 12.43it/s]
100%|██████████| 32/32 [00:02<00:00, 12.91it/s]
 Site-0| Train Acc: 97.2313
 Site-0| Val  Acc: 97.3105
 Site-1| Train Acc: 99.2176
 Site-1| Val  Acc: 99.3590
 Site-2| Train Acc: 100.0000
 Site-2| Val  Acc: 100.0000
 Test site-0| Test Acc: 97.5550
 Test site-1| Test Acc: 98.5043
 Test site-2| Test Acc: 99.7006
 Test site-3| Test Acc: 89.1575
One epoc takes time: 31.47s
============ Train epoch 2 ============
100%|██████████| 39/39 [00:02<00:00, 13.64it/s]
100%|██████████| 44/44 [00:03<00:00, 13.76it/s]
100%|██████████| 32/32 [00:02<00:00, 13.73it/s]
 Site-0| Train Acc: 97.2313
 Site-0| Val  Acc: 97.0660
 Site-1| Train Acc: 99.2176
 Site-1| Val  Acc: 99.3590
 Site-2| Train Acc: 100.0000
 Site-2| Val  Acc: 100.0000
 Test site-0| Test Acc: 97.5550
 Test site-1| Test Acc: 98.7179
 Test site-2| Test Acc: 99.7006
  0%|          | 0/39 [00:00<?, ?it/s] Test site-3| Test Acc: 89.0812
One epoc takes time: 30.90s
============ Train epoch 3 ============
100%|██████████| 39/39 [00:02<00:00, 13.50it/s]
100%|██████████| 44/44 [00:03<00:00, 14.01it/s]
100%|██████████| 32/32 [00:02<00:00, 13.75it/s]
 Site-0| Train Acc: 97.2313
 Site-0| Val  Acc: 97.0660
 Site-1| Train Acc: 99.2176
 Site-1| Val  Acc: 99.3590
 Site-2| Train Acc: 100.0000
 Site-2| Val  Acc: 100.0000
 Test site-0| Test Acc: 97.5550
 Test site-1| Test Acc: 98.7179
 Test site-2| Test Acc: 99.7006
 Test site-3| Test Acc: 89.0048
One epoc takes time: 30.68s
============ Train epoch 4 ============
100%|██████████| 39/39 [00:02<00:00, 13.59it/s]
100%|██████████| 44/44 [00:03<00:00, 13.75it/s]
100%|██████████| 32/32 [00:02<00:00, 13.56it/s]
 Site-0| Train Acc: 97.3127
 Site-0| Val  Acc: 97.0660
 Site-1| Train Acc: 99.2176
 Site-1| Val  Acc: 99.3590
 Site-2| Train Acc: 100.0000
 Site-2| Val  Acc: 100.0000
 Test site-0| Test Acc: 97.5550
 Test site-1| Test Acc: 98.7179
 Test site-2| Test Acc: 99.7006
 Test site-3| Test Acc: 89.0303
One epoc takes time: 30.87s

I would be very grateful if you could spare some time to fix this bug. Thank you for your patience.

**Comment by lw0517** [comment]
I apologize, but we are unable to reproduce the bug you reported. We have used the codebase and executed it on a 3090, and there is no issue similar to what you described. Perhaps you could carefully check the environment, run scripts, and review the code modifications you made.
![image](https://github.com/microsoft/PersonalizedFL/assets/31000480/3eb17bcd-f319-4468-b7df-1db4fc6e32e1)
