### ISSUE TITLE
The dataset cannot be downloaded

### ISSUE THREAD

**Issue by Daisy-bit** [microsoft/PersonalizedFL#4]
Dear Author: 

The dataset in your tutorial cannot be downloaded. Could you restore it as soon as possible? Thank you.

**Comment by jindongwang** [comment]
@Daisy-bit I see. It looks like the public download has been disenabled. I'll update another address later and let you know.

**Comment by jindongwang** [comment]
@Daisy-bit I have updated the dataset download link. You can refresh the readme file for new links.

**Comment by Daisy-bit** [comment]
> @Daisy-bit I have updated the dataset download link. You can refresh the readme file for new links.

Thanks for your reply. The community is more friendly because of you.
