### ISSUE TITLE
About method getallfea() in models

### ISSUE THREAD

**Issue by KarhouTam** [microsoft/PersonalizedFL#5]
Hi, your work is very inspiring. 
I found some codes about extracting the features made me confused. And I wonder if it is on purpose.
In `models.py`, method `getallfea()` in classes `PamapModel`, and `lenet5v` sometimes put the output of `conv` layers into the `fealist` but not the output of `bn` layers. 
But in class `AlexNet`, method `getallfea()`'s features are all outputs of `bn` layers.
Is it right?
![image](https://user-images.githubusercontent.com/82705454/199189856-ce9e333c-967b-4fd6-a84d-b6b417ffa467.png)

**Comment by lw0517** [comment]
> Hi, your work is very inspiring. I found some codes about extracting the features made me confused. And I wonder if it is on purpose. In `models.py`, method `getallfea()` in classes `PamapModel`, and `lenet5v` sometimes put the output of `conv` layers into the `fealist` but not the output of `bn` layers. But in class `AlexNet`, method `getallfea()`'s features are all outputs of `bn` layers. Is it right? ![image](https://user-images.githubusercontent.com/82705454/199189856-ce9e333c-967b-4fd6-a84d-b6b417ffa467.png)

There is no uniform guideline for which layers to choose. You can view the choice as a hyperparameter. Both the output of conv layers and the output of bn layers can serve as the fealist. If you have enough time and resources, you can try both of them and select the best one.
