### ISSUE TITLE
cannot download the dataset

### ISSUE THREAD

**Issue by tenstep** [microsoft/PersonalizedFL#6]
the download link is invalid.
`<Error>
<Code>AccountIsDisabled</Code>
<Message>The specified account is disabled. RequestId:898e522c-e01e-002d-0fde-0a0e8b000000 Time:2022-12-08T08:21:34.5410795Z</Message>
</Error>`

**Comment by jindongwang** [comment]
Hi, this is because this Azure subscription runs out of cost. You can now download them. Try again.

**Comment by tenstep** [comment]
wow, thanks!
