### ISSUE TITLE
Did you use multi-thread code?

### ISSUE THREAD

**Issue by FibonacciZ** [microsoft/PersonalizedFL#7]
When I trained on the dataset you provided，My GPU memory is higher than training on cifar10(added by me) and training faster than on cifar10. 
Did you use multi-thread code(I try to found this, but I failed).

GPU 0 is training on cifar10.
GPU 1 is training on covid.
![WB )ZUYMY81OZN5R}SNFJ$5](https://user-images.githubusercontent.com/27908488/225638966-42553c01-29e9-4ddf-b5bc-7b666c6ca9d1.png)

**Comment by jindongwang** [comment]
@lw0517

**Comment by lw0517** [comment]
> When I trained on the dataset you provided，My GPU memory is higher than training on cifar10(added by me) and training faster than on cifar10. Did you use multi-thread code(I try to found this, but I failed).
> 
> GPU 0 is training on cifar10. GPU 1 is training on covid. ![WB )ZUYMY81OZN5R}SNFJ$5](https://user-images.githubusercontent.com/27908488/225638966-42553c01-29e9-4ddf-b5bc-7b666c6ca9d1.png)

We did not use multi-thread code. If you want to use multi-thread, ray can be a choice.

Different GPU memory usage can be caused by lots of factors, e.g. different batch sizes, different backbones, and so on. From the information you have provided so far, I cannot find the exact reasons.
